### ISSUE TITLE
‘sudo ruby mydns.rb’遇错，

### ISSUE THREAD

**Issue by luckypoem** [mikechen163/mydns#2]
hi.

在mac上。
$ sudo ruby mydns.rb
Password:
Traceback (most recent call last):
	4: from mydns.rb:6:in `<main>'
	3: from mydns.rb:6:in `require_relative'
	2: from /Users/yuming/mydns-by-mikechen163/lib/myresolver.rb:5:in `<top (required)>'
	1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- celluloid/io (LoadError)

如何解决？谢谢

**Comment by mikechen163** [comment]
try the following 

sudo gem install celluloid-io --no-doc --no-ri

**Comment by luckypoem** [comment]
hi.

运行了sudo gem install celluloid-io ，不过还是遇错：
yudeMacBook-Air:mydns-by-mikechen163 brite$ sudo ruby mydns.rb
I, [2019-11-11T01:39:11.739880 #56959]  INFO -- : Celluloid 0.17.4 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
Traceback (most recent call last):
	4: from mydns.rb:9:in `<main>'
	3: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/psych.rb:277:in `load'
	2: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/psych.rb:390:in `parse'
	1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/psych.rb:456:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1 (Psych::SyntaxError)
yudeMacBook-Air:mydns-by-mikechen163 brite$

怎么解决？
